// --- Day 7: Laboratories ---
// You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

// Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

// Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

// Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

// You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

// For example:

// .......S.......
// ...............
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

// .......S.......
// .......|.......
// .......^.......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// At that point, the original beam stops, and two new beams are emitted from the splitter:

// .......S.......
// .......|.......
// ......|^|......
// ...............
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// Those beams continue downward until they reach more splitters:

// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// ......^.^......
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// .....|^|^|.....
// ...............
// .....^.^.^.....
// ...............
// ....^.^...^....
// ...............
// ...^.^...^.^...
// ...............
// ..^...^.....^..
// ...............
// .^.^.^.^.^...^.
// ...............
// This process continues until all of the tachyon beams reach a splitter or exit the manifold:

// .......S.......
// .......|.......
// ......|^|......
// ......|.|......
// .....|^|^|.....
// .....|.|.|.....
// ....|^|^|^|....
// ....|.|.|.|....
// ...|^|^|||^|...
// ...|.|.|||.|...
// ..|^|^|||^|^|..
// ..|.|.|||.|.|..
// .|^|||^||.||^|.
// .|.|||.||.||.|.
// |^|^|^|^|^|||^|
// |.|.|.|.|.|||.|
// To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

// Analyze your manifold diagram. How many times will the beam be split?

let exampleLines = 
    [|
        ".......S......."
        "..............."
        ".......^......."
        "..............."
        "......^.^......"
        "..............."
        ".....^.^.^....."
        "..............."
        "....^.^...^...."
        "..............."
        "...^.^...^.^..."
        "..............."
        "..^...^.....^.."
        "..............."
        ".^.^.^.^.^...^."
        "..............."
    |]
    
let fileLines = System.IO.File.ReadAllLines(System.IO.Path.Combine(__SOURCE_DIRECTORY__, "Day7.txt"))

let up (x, y) = (x, y - 1)
let down (x, y) = (x, y + 1)
let left (x, y) = (x - 1, y)
let right (x, y) = (x + 1, y)
let upLeft (x, y) = (x - 1, y - 1)
let upRight (x, y) = (x + 1, y - 1)
let downLeft (x, y) = (x - 1, y + 1)
let downRight (x, y) = (x + 1, y + 1)
let inBounds (width, height) (x, y) = x >= 0 && x < width && y >= 0 && y < height

let getChar (width, height) (data: string[]) (x, y) =
    if inBounds (width, height) (x, y)
    then Some(data[y][x])
    else None

let findStart (lines: string[]) =
    let y = lines |> Array.findIndex (fun line -> line.Contains("S"))
    let x = lines[y].IndexOf("S")
    (x, y)


let traverse lines =
    let width = lines |> Array.head |> String.length
    let height = lines |> Array.length
    let start = findStart lines
    let getChar' = getChar (width, height) lines
    let splits = System.Collections.Generic.List()
    let beams = System.Collections.Generic.List()
    beams.Add start

    let rec tick'() =
        for item in beams |> Seq.toArray do
            beams.Remove item |> ignore
            let below = down item
            match getChar' below with
            | Some('.') ->
                beams.Add below
            | Some('^') ->
                let leftPos = left below
                let rightPos = right below
                if not (splits.Contains below) then
                    splits.Add below
                if not (beams.Contains leftPos) then
                    beams.Add leftPos
                if not (beams.Contains rightPos) then
                    beams.Add rightPos
            | Some other -> failwithf "Unexpected char %c at %A" other below
            | None -> beams.Remove item |> ignore

    let printTree() =
        printfn "splits: %d" splits.Count
        for y in 0 .. height - 1 do
            for x in 0 .. width - 1 do
                let pos = (x, y)
                if beams.Contains pos then
                    printf "|"
                else
                    printf "%c" (lines[y][x])
            printfn ""
        printfn ""

    while beams.Count > 0 do
        printTree()
        System.Threading.Thread.Sleep 200
        tick'()
    splits.Count

let part1 = traverse exampleLines

// --- Part Two ---
// With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a quantum tachyon manifold.

// With a quantum tachyon manifold, only a single tachyon particle is sent through the manifold. A tachyon particle takes both the left and right path of each splitter encountered.

// Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually time itself which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.

// To fix the manifold, what you really need to know is the number of timelines active after a single particle completes all of its possible journeys through the manifold.

// In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:

// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ...|^.^...^....
// ...|...........
// ..|^.^...^.^...
// ..|............
// .|^...^.....^..
// .|.............
// |^.^.^.^.^...^.
// |..............
// Or, there's the timeline where the particle alternated going left and right at each splitter:

// .......S.......
// .......|.......
// ......|^.......
// ......|........
// ......^|^......
// .......|.......
// .....^|^.^.....
// ......|........
// ....^.^|..^....
// .......|.......
// ...^.^.|.^.^...
// .......|.......
// ..^...^|....^..
// .......|.......
// .^.^.^|^.^...^.
// ......|........
// Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:

// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ....^|^...^....
// .....|.........
// ...^.^|..^.^...
// ......|........
// ..^..|^.....^..
// .....|.........
// .^.^.^|^.^...^.
// ......|........
// In this example, in total, the particle ends up on 40 different timelines.

// Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. In total, how many different timelines would a single tachyon particle end up on?

let memoize f =
    let cache = System.Collections.Generic.Dictionary<_, _>()
    let rec memoized x =
        if cache.ContainsKey x then
            cache[x]
        else
            let result = f memoized x
            cache[x] <- result
            result
    memoized

let traverse2 lines =
    let cache = System.Collections.Generic.Dictionary<_, _>()
    let width = lines |> Array.head |> String.length
    let height = lines |> Array.length
    let start = findStart lines
    let getChar' = getChar (width, height) lines

    let rec loop = memoize (fun loop position ->
        let nextPosition = down position
        match getChar' nextPosition with
        | Some('.') ->
            loop nextPosition
        | Some('^') ->
            let leftPos = left nextPosition
            let rightPos = right nextPosition
            let leftTimelines = loop leftPos
            let rightTimelines = loop rightPos

            leftTimelines + rightTimelines
        | Some other -> failwithf "Unexpected char %c at %A" other nextPosition
        | None -> 1L
    )

    loop start

let part2 = traverse2 fileLines